//Source - https://www.randomlists.com/random-phobias
var phobias = [
    { "name":"Ablutophobia","detail":"fear of cleaning" },
    { "name":"Achluophobia","detail":"fear of darkness" },
    { "name":"Acrophobia","detail":"fear of heights" },
    { "name":"Agoraphobia","detail":"fear of open/public spaces" },
    { "name":"Agraphobia","detail":"fear of sexual abuse" },
    { "name":"Agrizoophobia","detail":"fear of wild animals" },
    { "name":"Agyrophobia","detail":"fear of crossing the road" },
    { "name":"Aichmophobia","detail":"fear of sharpness, knifes, needles" },
    { "name":"Ailurophobia","detail":"fear of cats" },
    { "name":"Algophobia","detail":"fear of pain" },
    { "name":"Amychophobia","detail":"fear of being scratched." },
    { "name":"Androphobia","detail":"fear of men" },
    { "name":"Anthophobia","detail":"fear of flowers" },
    { "name":"Anthropophobia","detail":"fear of people" },
    { "name":"Aquaphobia","detail":"fear of water" },
    { "name":"Arachnophobia","detail":"fear of spiders" },
    { "name":"Astraphobia","detail":"fear of thunder and lightning" },
    { "name":"Atychiphobia","detail":"fear of failure" },
    { "name":"Autophobia","detail":"fear of being alone" },
    { "name":"Automatonophobia","detail":"fear of humanoid figures" },
    { "name":"Aviatophobia","detail":"fear of flying" },
    { "name":"Chaetophobia","detail":"fear of hair" },
    { "name":"Chemophobia","detail":"fear of chemicals" },
    { "name":"Chiroptophobia","detail":"fear of bats" },
    { "name":"Chromophobia","detail":"fear of bright colors" },
    { "name":"Chronophobia","detail":"fear of time moving forward" },
    { "name":"Cibophobia","detail":"aversion to food" },
    { "name":"Claustrophobia","detail":"fear of having no escape" },
    { "name":"Coulrophobia","detail":"fear of clowns" },
    { "name":"Cyberphobia","detail":"fear of new technology" },
    { "name":"Decidophobia","detail":"fear of making decisions" },
    { "name":"Dentophobia","detail":"fear of dentists" },
    { "name":"Disposophobia","detail":"fear of diposing of things" },
    { "name":"Dysmorphophobia","detail":"obsession with a body defect" },
    { "name":"Emetophobia","detail":"fear of vomiting" },
    { "name":"Ergasiophobia","detail":"fear of working" },
    { "name":"Ergophobia","detail":"fear of work or functioning" },
    { "name":"Erotophobia","detail":"fear of sexual love/abuse" },
    { "name":"Erythrophobia","detail":"pathological blushing" },
    { "name":"Dikephobia","detail":"fear of law or justice" },
    { "name":"Frigophobia","detail":"fear of becoming too cold" },
    { "name":"Gamophobia","detail":"fear of marriage, commitment" },
    { "name":"Gelotophobia","detail":"fear of being laughed at" },
    { "name":"Gephyrophobia","detail":"fear of bridges" },
    { "name":"Coitophobia","detail":"fear of sexual intercourse" },
    { "name":"Gerascophobia","detail":"fear of growing old or aging" },
    { "name":"Gerontophobia","detail":"fear of growing old" },
    { "name":"Gerontophobia","detail":"fear of the elderly" },
    { "name":"Glossophobia","detail":"fear of speaking publicly" },
    { "name":"Gymnophobia","detail":"fear of nudity" },
    { "name":"Gynophobia","detail":"fear of women" },
    { "name":"Hadephobia","detail":"fear of Hell" },
    { "name":"Halitophobia","detail":"fear of bad breath" },
    { "name":"Haphephobia","detail":"fear of being touched" },
    { "name":"Heliophobia","detail":"fear of sunlight" },
    { "name":"Hemophobia","detail":"fear of blood" },
    { "name":"Hexakosioihexe-kontahexaphobia","detail":"fear of the number 666" },
    { "name":"Hoplophobia","detail":"fear of firearms" },
    { "name":"Homophobia","detail":"fear of homosexuals" },
    { "name":"Hylophobia","detail":"fear of trees, forests, wood" },
    { "name":"Hypnophobia","detail":"fear of sleep" },
    { "name":"Ichthyophobia","detail":"fear of fish" },
    { "name":"Ipovlopsychophobia","detail":"fear of being photographed" },
    { "name":"Lipophobia","detail":"fear fatty foods" },
    { "name":"Mysophobia","detail":"fear of germs/dirt" },
    { "name":"Necrophobia","detail":"fear of death" },
    { "name":"Necrophobia","detail":"fear of the dead" },
    { "name":"Neophobia","detail":"fear of new things" },
    { "name":"Nomophobia","detail":"fear of being out of mobile phone contact" },
    { "name":"Nosocomephobia","detail":"fear of hospitals" },
    { "name":"Nosophobia","detail":"fear of contracting disease" },
    { "name":"Nyctophobia","detail":"fear of darkness" },
    { "name":"Obesophobia","detail":"fear of obesity" },
    { "name":"Oikophobia","detail":"fear of household appliances/stuff" },
    { "name":"Ombrophobia","detail":"fear of rain" },
    { "name":"Omphalophobia","detail":"fear of bellybuttons" },
    { "name":"Ophthalmophobia","detail":"fear of being stared at" },
    { "name":"Ornithophobia","detail":"fear of birds" },
    { "name":"Osmophobia","detail":"fear of bad odours" },
    { "name":"Panphobia","detail":"fear of everything" },
    { "name":"Panphobia","detail":"constant fear without cause" },
    { "name":"Papaphobia","detail":"fear of the Pope" },
    { "name":"Pediophobia","detail":"fear of dolls" },
    { "name":"Phagophobia","detail":"fear of swallowing" },
    { "name":"Pharmacophobia","detail":"fear of medications" },
    { "name":"Philophobia","detail":"fear of love" },
    { "name":"Phobophobia","detail":"fear of fear/phobias" },
    { "name":"Phonophobia","detail":"fear of loud sounds" },
    { "name":"Pyrophobia","detail":"fear of fire" },
    { "name":"Radiophobia","detail":"fear of radioactivity, X-rays" },
    { "name":"Sesquipedalophobia","detail":"fear of long words" },
    { "name":"Scopophobia","detail":"fear of being looked at" },
    { "name":"Sociophobia","detail":"fear of social situations" },
    { "name":"Somniphobia","detail":"fear of sleep" },
    { "name":"Spectrophobia","detail":"fear of ghosts and phantoms" },
    { "name":"Stygiophobia","detail":"fear of Hell" },
    { "name":"Taphophobia","detail":"fear of the grave" },
    { "name":"Taphephobia","detail":"fear of being in grave while alive" },
    { "name":"Technophobia","detail":"fear of technology" },
    { "name":"Telephone phobia","detail":"fear of phone calls" },
    { "name":"Tetraphobia","detail":"fear of the number 4" },
    { "name":"Thalassophobia","detail":"fear of the sea" },
    { "name":"Thanatophobia","detail":"fear of dying" },
    { "name":"Thermophobia","detail":"fear of heat" },
    { "name":"Tokophobia","detail":"fear of childbirth, pregnancy" },
    { "name":"Traumatophobia","detail":"fear of having an injury" },
    { "name":"Triskaidekaphobia","detail":"fear of the number 13" },
    { "name":"Trypanophobia","detail":"fear of needles or injections" },
    { "name":"Trypophobia","detail":"fear of holes" },
    { "name":"Uranophobia","detail":"fear of Heaven" },
    { "name":"Xanthophobia","detail":"fear of the color yellow" },
    { "name":"Xenophobia","detail":"fear of strangers, foreigners, aliens" },
    { "name":"Xylophobia","detail":"fear of trees, forests or wood" },
    { "name":"Agrizoophobia","detail":"fear of wild animals" },
    { "name":"Ailurophobia","detail":"fear of cats" },
    { "name":"Apiphobia","detail":"fear of bees" },
    { "name":"Arachnophobia","detail":"fear of spiders" },
    { "name":"Bovinophobia","detail":"fear of cattle" },
    { "name":"Chiroptophobia","detail":"fear of bats" },
    { "name":"Cynophobia","detail":"fear of dogs" },
    { "name":"Entomophobia","detail":"fear of insects" },
    { "name":"Equinophobia","detail":"fear of horses" },
    { "name":"Herpetophobia","detail":"fear of reptiles" },
    { "name":"Ichthyophobia","detail":"fear of fish" },
    { "name":"Mottephobia","detail":"fear of butterflies, moths" },
    { "name":"Murophobia","detail":"fear of mice, rats" },
    { "name":"Ophidiophobia","detail":"fear of snakes" },
    { "name":"Ornithophobia","detail":"fear of birds" },
    { "name":"Ranidaphobia","detail":"fear of frogs" },
    { "name":"Selachophobia","detail":"fear of sharks" },
    { "name":"Scoleciphobia","detail":"fear of worms" },
    { "name":"Zoophobia","detail":"fear of animals" },
    { "name":"Anglophobia","detail":"fear of England" },
    { "name":"Atheophobia","detail":"fear of atheists" },
    { "name":"Biphobia","detail":"fear of bisexuality" },
    { "name":"Christianophobia","detail":"fear of Christians" },
    { "name":"Ephebiphobia","detail":"fear of youth" },
    { "name":"Germanophobia","detail":"fear of Germans" },
    { "name":"Gerontophobia","detail":"fear of the elderly" },
    { "name":"Heterophobia","detail":"fear of heterosexuality" },
    { "name":"Homophobia","detail":"fear of homosexuality" },
    { "name":"Islamophobia","detail":"fear of Muslims" },
    { "name":"Judeophobia","detail":"fear of Jews." },
    { "name":"Lesbophobia","detail":"fear of lesbians" },
    { "name":"Negrophobia","detail":"fear of Black people" },
    { "name":"Nipponophobia","detail":"fear of the Japanese" },
    { "name":"Pedophobia","detail":"fear of children" },
    { "name":"Polonophobia","detail":"fear of the Polish" },
    { "name":"Psychophobia","detail":"fear of mental illness" },
    { "name":"Russophobia","detail":"fear of the Russians" },
    { "name":"Sinophobia","detail":"fear of Chinese" },
    { "name":"Transphobia","detail":"fear of transgendered people" },
    { "name":"Turcophobia","detail":"fear of the Turks" },
    { "name":"Xenophobia","detail":"fear of foreigners, extraterrestrials" }
 ]
 var phobia = {
     generate : function() {
        return phobias[Math.floor(Math.random() * 154)].name
     },
     length : function() {
         return phobias.length
     }
 }