//Source - https://www.randomlists.com/team-names
var team_names = {"1":["Awkward","Bald","Big","Black","Blue","Cajun","Coy","Dangerous","Defective","Delta","Demon","Deranged","Educated","Fanatical","Festive","Fighting","Flaming","Flawless","Flying","Glistening","Golden","Graceful","Great","Green","Grotesque","Hideous","Horned","Horrible","Lady","Little","Mad","Marvelous","Mean","Mighty","Obscene","Odd","Old","Orange","Overconfident","Polar","Powerful","Prairie","Punctual","Purple","Red","Remarkable","Running","Sassy","Screaming","Seemly Short","Serious","Silver","Simple","Solemn","Somber","Spicy","Strange","Sugar","Supreme","Swift","Threatening","Thundering","Ultimate","Unaccountable","Unethical","Voodoo","Weak","Wet","White","Wicked","Winter","Wonderful"],"2":["Aces","Anchormen","Archers","Artichokes","Avengers","Badgers","Battlers","Bearcats","Bears","Beavers","Bees","Belles","Bengals","Bison","Blazers","Bloodhounds","Blossoms","Bluejays","Blues","Bobcats","Bombers","Boys","Braves","Brewers","Broncos","Bruins","Buccaneers","Buckeyes","Buffaloes","Bulldogs","Bullets","Bulls","Cadets","Camels","Captains","Cardinals","Catamounts","Cats","Cavaliers","Chargers","Chiefs","Clippers","Cobras","Colonels","Colonials","Colts","Comets","Commodores","Conquerors","Cougars","Cowboys","Cowgirls","Coyotes","Crusaders","Cubs","Cyclones","Defenders","Demons","Devilettes","Devils","Dodgers","Dolphins","Dragons","Ducks","Dutchmen","Eagles","Engineers","Explorers","Express","Falcons","Fire","Firebirds","Flames","Flash","Fleet","Flyers","Foresters","Foxes","Friars","Frogs","Gamecocks","Gators","Generals","Gentlemen","Giants","Gladiators","Gophers","Gorillas","Governors","Greyhounds","Griffins","Grizzlies","Hawkeyes","Hawks","Heels","Highlanders","Hobos","Hornets","Hurricanes","Huskies","Indians","Islanders","Jackrabbits","Jaguars","Janes","Jays","Jets","Jimmies","Johnnies","Kangaroos","Kingsmen","Knights","Kohawks","Ladies","Lakers","Lancers","Leopards","Lightning","Lions","Llamas","Longhorns","Magicians","Marauders","Maroons","Mavericks","Men","Miners","Minutemen","Monarchs","Monks","Monsters","Mountaineers","Mules","Musketeers","Mustangs","Nighthawks","Oaks","Ocelots","Oilers","Outlaws","Owls","Pacers","Paladins","Panthers","Patriots","Peacocks","Penguins","Pickles","Pilots","Pioneers","Pirates","Poets","Pointers","Pride","Princes","Princesses","Privateers","Racers","Raiders","Rainbows","Ramblers","Rams","Rangers","Raptors","Rattlesnakes","Ravens","Razorbacks","Rebels","Reds","Redskins","Rockets","Rocks","Royals","Rustlers","Saints","Seagulls","Seahawks","Seawolves","Senators","Sharks","Sox","Spartans","Spiders","Squirrels","Stags","Stallions","Stars","Storm","Sunbirds","Suns","Thunder","Thunderbirds","Tigers","Titans","Tornadoes","Trailblazers","Trojans","Trolls","Vandals","Vikings","Vixens","Volunteers","Vulcans","Warriors","Wave","Wildcats","Wolfpack","Wolverines","Wolves","Wombats","Women","Yellowjackets"]}
var team_name = {
    generate : function() {
        return team_names[1][Math.floor(Math.random() * 72)] + " " + team_names[2][Math.floor(Math.random() * 212)]
    },
    length : function() {
        return team_names[1].length * team_names[2].length
    }
}